export enum AppNode {
  DEFAULT = '',
  PUBLIC = '',
  SHOP = 'shop',
  DASHBOARD = 'dashboard',
  SIGN_UP = 'sign-up',
  FORGOT_PASSWORD = 'forgot-password',
  ABOUT_US = 'about-us',
  JOBS = 'jobs',
  OUR_VALUE = 'our-value',
  JOIN_US = 'join-us',
  REDIRECT_TO_PUBLIC = AppNode.DEFAULT,
  REDIRECT_TO_AUTHENTICATED = AppNode.DASHBOARD,
  FALL_BACK = '**',
  HOME = 'home',
  MENU = 'menu',
  CART = 'cart',
  NOTIFICATION = 'notifications',
  ACCOUNT = 'account',
  ORDERS = 'orders',
}
