export enum AppNode {
  DEFAULT = '',
  PUBLIC = '',
  LIST = 'list',
  DETAIL = 'detail/',
  DASHBOARD = 'dashboard',
  SIGN_UP = 'sign-up',
  FORGOT_PASSWORD = 'forgot-password',
  ABOUT_US = 'about-us',
  JOBS = 'jobs',
  OUR_VALUE = 'our-value',
  JOIN_US = 'join-us',
  REDIRECT_TO_PUBLIC = AppNode.DEFAULT,
  REDIRECT_TO_AUTHENTICATED = AppNode.DASHBOARD,
  FALL_BACK = '**',
  ACCOUNT = 'account',
}
