export enum ApiCodeResponse {
  COMMON = 'COMMON',
  COMMON_SUCCESS = 'api.common.success',
  NO_TOKEN_FOUNDED = 'NO_TOKEN_FOUNDED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  SIGNUP_ERROR = 'SIGNUP_ERROR',
  CREDENTIAL_DELETE_ERROR = 'CREDENTIAL_DELETE_ERROR',
  USER_ALREADY_EXIST = 'USER_ALREADY_EXIST',
  TOKEN_GEN_ERROR = 'TOKEN_GEN_ERROR'

}